keyset=_gauss_int32
data.size=_1e5

train.seed=42
train.learning.rate=0.05
train.batch.size=32
train.epochs=100
net.hidden.layers=4,4
plot.path=plot.pdf

workload.distribution=_uniform
workload.permutation=_false
workload.factor=_read_only
max.err=_0
